fi_pannello_amministrazione_homepage:
    path:  /adminpanel
    defaults: { _controller: FiPannelloAmministrazioneBundle:Default:index }

fi_pannello_amministrazione_clearcache:
    path:  /adminpanel/clearcache
    defaults: { _controller: FiPannelloAmministrazioneBundle:Default:clearCache }

fi_pannello_amministrazione_chown:
    path:  /adminpanel/chown
    defaults: { _controller: FiPannelloAmministrazioneBundle:Default:chown }

fi_pannello_amministrazione_getSvn:
    path:  /adminpanel/getSvn
    defaults: { _controller: FiPannelloAmministrazioneBundle:Default:getSvn }

fi_pannello_amministrazione_getGit:
    path:  /adminpanel/getGit
    defaults: { _controller: FiPannelloAmministrazioneBundle:Default:getGit }

fi_pannello_amministrazione_generateentity:
    path:  /adminpanel/generateEntity
    defaults: { _controller: FiPannelloAmministrazioneBundle:Default:generateEntity }

fi_pannello_amministrazione_generateentityclass:
    path:  /adminpanel/generateEntityClass
    defaults: { _controller: FiPannelloAmministrazioneBundle:Default:generateEntityClass }

fi_pannello_amministrazione_dropdatabase:
    path:  /adminpanel/dropDatabase
    defaults: { _controller: FiPannelloAmministrazioneBundle:Default:dropdatabase }
    
fi_pannello_amministrazione_dropdatabaseconfirm:
    path:  /adminpanel/dropDatabaseConfirm
    defaults: { _controller: FiPannelloAmministrazioneBundle:Default:dropdatabaseconfirm }

fi_pannello_amministrazione_aggiornaschemadatabase:
    path:  /adminpanel/aggiornaschemadatabase
    defaults: { _controller: FiPannelloAmministrazioneBundle:Default:aggiornaSchemaDatabase }

fi_pannello_amministrazione_generatebundle:
    path:  /adminpanel/generateBundle
    defaults: { _controller: FiPannelloAmministrazioneBundle:Default:generateBundle }

fi_pannello_amministrazione_generateform:
    path:  /adminpanel/generateForm
    defaults: { _controller: FiPannelloAmministrazioneBundle:Default:generateForm }

fi_pannello_amministrazione_generateformcrud:
    path:  /adminpanel/generateFormCrud
    defaults: { _controller: FiPannelloAmministrazioneBundle:Default:generateFormCrud }

fi_pannello_amministrazione_symfonycommand:
    path:  /adminpanel/symfonyCommand
    defaults: { _controller: FiPannelloAmministrazioneBundle:Default:symfonyCommand }

fi_pannello_amministrazione_unixcommand:
    path:  /adminpanel/unixCommand
    defaults: { _controller: FiPannelloAmministrazioneBundle:Default:unixCommand }

fi_pannello_amministrazione_phpunittest:
    path:  /adminpanel/phpunittest
    defaults: { _controller: FiPannelloAmministrazioneBundle:Default:phpunittest }
