
language: php

php:
  - 5.6
  - 7.0

before_script:
  - phpenv config-add travis.php.ini
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - composer install
  - php src/Tests/app/console fifree:install admin admin admin@admin.it --env=test
  - php src/Tests/app/console assets:install src/Tests/app --env=test
  - php src/Tests/app/console server:run -d src/Tests/app --env=test 2>&1 &
  - sh vendor/bin/selenium-server-standalone > /dev/null 2>&1 &
  - chmod 777 src/Tests/app/dbtest.sqlite
  - rm -rf src/Tests/app/cache/test
  - rm -rf src/Tests/app/cache/dev

script:
  - rm -rf src/Tests/app/cache/test
  - rm -rf src/Tests/app/cache/dev
  - ant

after_success:
  - if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then php vendor/satooshi/php-coveralls/bin/coveralls -v; fi
  - vendor/bin/security-checker -n security:check

notifications:
  email:
  - andrea.manzi@libero.it
