
language: php

php:
  - 5.6
  - 7.0

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - composer install
  - php src/Tests/app/console fifree:install admin admin admin@admin.it
  - php src/Tests/app/console assets:install src/Tests/app
  - php src/Tests/app/console server:run -d src/Tests/app
  - sh vendor/bin/selenium-server-standalone > /dev/null 2>&1 &

script:
  - ant

after_success:
  - if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then php vendor/satooshi/php-coveralls/bin/coveralls -v; fi
  - vendor/bin/security-checker -n security:check

notifications:
  email:
  - andrea.manzi@libero.it
