
language: php

php:
  - 5.6
  - 7.0

before_script:
  - composer install

script:
  - ant

after_success:
  - if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then php vendor/satooshi/php-coveralls/bin/coveralls -v; fi
  - bin/security-checker -n security:check

notifications:
  email:
  - andrea.manzi@libero.it
