
language: php

php:
  - 5.6
  - 7.0

before_script:
  - composer install
  - php src/Tests/app/console fifree:install admin admin admin@admin.it
  - php src/Tests/app/console assets:install src/Tests/app
  - php src/Tests/app/console server:run -d src/Tests/app

script:
  - ant

after_success:
  - if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then php vendor/satooshi/php-coveralls/bin/coveralls -v; fi
  - vendor/bin/security-checker -n security:check

notifications:
  email:
  - andrea.manzi@libero.it
